import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import React, { useState, useEffect, useRef } from 'react';

export default function Home() {
  const [slideIndex, setSlideIndex] = useState(0);
  const slideRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const interval = setInterval(() => {
      slideNext();
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  const slideNext = () => {
    setSlideIndex((prevIndex) => (prevIndex + 1) % 4);
  };

  const slideDown = () => {
    if (slideRef.current) {
      slideRef.current.style.transform = `translateY(-${slideIndex * 100}%)`;
    }
  };

  return (
    <>
      <div
        style={{
          position: 'fixed',
          top: '100%',
          left: 0,
          width: '100%',
          height: '100%',
          zIndex: -1,
          overflow: 'hidden',
        }}
      ></div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          position: 'relative',
          width: '100%',
          height: '400%',
          transition: 'transform 0.5s',
          transform: `translateY(-${slideIndex * 100}%)`,
        }}
        ref={slideRef}
      >
       
        <div style={{ position: 'relative', width: '100%', height: '25%' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', overflow: 'hidden' }}>
            <Image src="/assets/01.jpg" alt="Slide 1" layout="fill" objectFit="cover" />
          </div>
        </div>
     
        <div style={{ position: 'relative', width: '100%', height: '25%' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', overflow: 'hidden' }}>
            <Image src="/assets/02.jpg" alt="Slide 2" layout="fill" objectFit="cover" />
          </div>
        </div>
       
        <div style={{ position: 'relative', width: '100%', height: '25%' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', overflow: 'hidden' }}>
            <Image src="/assets/03.jpg" alt="Slide 3" layout="fill" objectFit="cover" />
          </div>
        </div>
      
        <div style={{ position: 'relative', width: '100%', height: '25%' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', overflow: 'hidden' }}>
            <Image src="/assets/04.jpg" alt="Slide 4" layout="fill" objectFit="cover" />
          </div>
        </div>
      </div>

  
      <div
        style={{
          position: 'fixed',
          bottom: '20px',
          left: '50%',
          transform: 'translateX(-50%)',
          zIndex: 1,
        }}
      >
       
      </div>

    
    </>
  );
}
