import './globals.css'
import { Inter } from 'next/font/google'
import Search from './search/search'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    <Search/>
    </div>
  )
}
